version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore_cache:
          keys:
              - sfdx-version-42-local
      - run:
          name: Install Salesforce DX
          command: |
              openssl aes-256-cbc -k $KEY -in .circleci/server.key.enc -out .circleci/server.key -d
              export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
              export SFDX_DOMAIN_RETRY=300
              npm install sfdx-cli
              node_modules/sfdx-cli/bin/run --version
              node_modules/sfdx-cli/bin/run plugins --core
      - save_cache:
          key: sfdx-version-42-local
          paths:
              - node_modules
      - run:
          name: Authenticate DevHub
          command: |
              node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile .circleci/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
      - run:
          name: Create Scratch Org 1
          command: |
              node_modules/sfdx-cli/bin/run force:org:create -v DevHub -s -f config/project-scratch-def.json -a ciorg
      - run:
          name: Push Source
          command: |
             node_modules/sfdx-cli/bin/run force:source:push -u ciorg
      - run:
          name: Run Apex Tests
          command: |
              node_modules/sfdx-cli/bin/run force:apex:test:run -u ciorg -c -r human -w 10
      - run:
          name: Clean Up
          when: always
          command: |
              node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p
      - run:
          name: Create Scratch Org 2
          command: |
              node_modules/sfdx-cli/bin/run force:org:create -v DevHub -s -f config/project-scratch-def.json -a ciorg
      - run:
          name: Install Project
          command: |
              node_modules/sfdx-cli/bin/run force:package:install --wait 10 --publishwait 10 --package snap_package@1.0.0-1 -k test1234 -r -u ciorg
      - run:
          name: Run Apex Tests
          command: |
              node_modules/sfdx-cli/bin/run force:apex:test:run -u ciorg -c -r human -w 10
      - run:
          name: Clean Up
          when: always
          command: |
              node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p